### ISSUE TITLE
I feel like I don't have OCD....

### ISSUE THREAD

**Issue by PatrickAlphaC** [maticmike/contracts#1]
But I felt like I needed to make this issue.

Could we remove the space in `MaticMike Contract`?

Amazing project btw 😆

**Comment by maticmike** [comment]
Yeah definitely, I will update this after hackathon judgement, don't want to commit any changes (even folder changes) while judging is taking place.

Thank you for the kind words about the project, this is my first hackathon :)

**Comment by maticmike** [comment]
Renamed folders in the commit to help Patrick with his OCD, as well as just have more standard naming conventions.
